# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/AddressBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddressBook(object):
    def setupUi(self, AddressBook):
        AddressBook.setObjectName("AddressBook")
        AddressBook.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AddressBook)
        self.centralwidget.setObjectName("centralwidget")
        AddressBook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddressBook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        AddressBook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddressBook)
        self.statusbar.setObjectName("statusbar")
        AddressBook.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(AddressBook)
        self.action_Quit.setObjectName("action_Quit")
        self.menu_File.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(AddressBook)
        QtCore.QMetaObject.connectSlotsByName(AddressBook)

    def retranslateUi(self, AddressBook):
        _translate = QtCore.QCoreApplication.translate
        AddressBook.setWindowTitle(_translate("AddressBook", "Address Book"))
        self.menu_File.setTitle(_translate("AddressBook", "&File"))
        self.action_Quit.setText(_translate("AddressBook", "&Quit"))
        self.action_Quit.setShortcut(_translate("AddressBook", "Ctrl+Q"))
