# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Municipality.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Municipality(object):
    def setupUi(self, Municipality):
        Municipality.setObjectName("Municipality")
        Municipality.resize(1098, 797)
        self.verticalLayout = QtWidgets.QVBoxLayout(Municipality)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Municipality)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pvp_building_municipalityName = QtWidgets.QLineEdit(self.groupBox_3)
        self.pvp_building_municipalityName.setText("")
        self.pvp_building_municipalityName.setReadOnly(True)
        self.pvp_building_municipalityName.setObjectName("pvp_building_municipalityName")
        self.horizontalLayout_20.addWidget(self.pvp_building_municipalityName)
        self.pvp_building_municipalityCode = QtWidgets.QLineEdit(self.groupBox_3)
        self.pvp_building_municipalityCode.setText("")
        self.pvp_building_municipalityCode.setReadOnly(True)
        self.pvp_building_municipalityCode.setObjectName("pvp_building_municipalityCode")
        self.horizontalLayout_20.addWidget(self.pvp_building_municipalityCode)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 0, 1, 2, 1)
        self.openMunicipalityWebsite = QtWidgets.QPushButton(self.groupBox_3)
        self.openMunicipalityWebsite.setObjectName("openMunicipalityWebsite")
        self.gridLayout_6.addWidget(self.openMunicipalityWebsite, 1, 2, 2, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 2, 0, 1, 1)
        self.obj_website = QtWidgets.QLineEdit(self.groupBox_3)
        self.obj_website.setText("")
        self.obj_website.setReadOnly(True)
        self.obj_website.setObjectName("obj_website")
        self.gridLayout_6.addWidget(self.obj_website, 2, 1, 2, 1)
        self.createBuildingForm = QtWidgets.QPushButton(self.groupBox_3)
        self.createBuildingForm.setObjectName("createBuildingForm")
        self.gridLayout_6.addWidget(self.createBuildingForm, 3, 2, 2, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 4, 0, 1, 1)
        self.evu_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.evu_5.setText("")
        self.evu_5.setReadOnly(True)
        self.evu_5.setObjectName("evu_5")
        self.gridLayout_6.addWidget(self.evu_5, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.createGvzDocumentation = QtWidgets.QPushButton(Municipality)
        self.createGvzDocumentation.setObjectName("createGvzDocumentation")
        self.verticalLayout.addWidget(self.createGvzDocumentation)
        self.frame_9 = QtWidgets.QFrame(Municipality)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout.addWidget(self.frame_9)

        self.retranslateUi(Municipality)
        QtCore.QMetaObject.connectSlotsByName(Municipality)

    def retranslateUi(self, Municipality):
        _translate = QtCore.QCoreApplication.translate
        Municipality.setWindowTitle(_translate("Municipality", "Form"))
        self.groupBox_3.setTitle(_translate("Municipality", "Gemeinde"))
        self.label_16.setText(_translate("Municipality", "Gemeinde / Nummer"))
        self.openMunicipalityWebsite.setText(_translate("Municipality", "Webseite öffnen"))
        self.label_46.setText(_translate("Municipality", "Webseite"))
        self.createBuildingForm.setText(_translate("Municipality", "Solarmeldung erstellen"))
        self.label_18.setText(_translate("Municipality", "Meldeformular"))
        self.createGvzDocumentation.setText(_translate("Municipality", "GVZ Dokumentation"))
