# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/PowerCompany.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PowerCompany(object):
    def setupUi(self, PowerCompany):
        PowerCompany.setObjectName("PowerCompany")
        PowerCompany.resize(1088, 864)
        self.verticalLayout = QtWidgets.QVBoxLayout(PowerCompany)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(PowerCompany)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.obj_name = QtWidgets.QLineEdit(self.groupBox_5)
        self.obj_name.setText("")
        self.obj_name.setReadOnly(True)
        self.obj_name.setObjectName("obj_name")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.obj_name)
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setObjectName("label_28")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.evu_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.evu_3.setText("")
        self.evu_3.setReadOnly(True)
        self.evu_3.setObjectName("evu_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.evu_3)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.obj_tagContact_email = QtWidgets.QLineEdit(self.groupBox_5)
        self.obj_tagContact_email.setText("")
        self.obj_tagContact_email.setReadOnly(True)
        self.obj_tagContact_email.setObjectName("obj_tagContact_email")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.obj_tagContact_email)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.composeTagEmail = QtWidgets.QPushButton(PowerCompany)
        self.composeTagEmail.setObjectName("composeTagEmail")
        self.gridLayout_7.addWidget(self.composeTagEmail, 1, 0, 1, 1)
        self.createMundpp = QtWidgets.QPushButton(PowerCompany)
        self.createMundpp.setObjectName("createMundpp")
        self.gridLayout_7.addWidget(self.createMundpp, 2, 0, 1, 1)
        self.createTag = QtWidgets.QPushButton(PowerCompany)
        self.createTag.setObjectName("createTag")
        self.gridLayout_7.addWidget(self.createTag, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(PowerCompany)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_7.addWidget(self.frame_10, 0, 1, 3, 1)
        self.frame_11 = QtWidgets.QFrame(PowerCompany)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7.addWidget(self.frame_11, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)

        self.retranslateUi(PowerCompany)
        QtCore.QMetaObject.connectSlotsByName(PowerCompany)

    def retranslateUi(self, PowerCompany):
        _translate = QtCore.QCoreApplication.translate
        PowerCompany.setWindowTitle(_translate("PowerCompany", "Form"))
        self.groupBox_5.setTitle(_translate("PowerCompany", "Netzbetreiber"))
        self.label_24.setText(_translate("PowerCompany", "Netzbetreiber"))
        self.label_28.setText(_translate("PowerCompany", "Kontakt"))
        self.label_27.setText(_translate("PowerCompany", "Anschlussgesuch"))
        self.composeTagEmail.setText(_translate("PowerCompany", "TAG E-Mail"))
        self.createMundpp.setText(_translate("PowerCompany", "M+PP erstellen"))
        self.createTag.setText(_translate("PowerCompany", "Anschlussgesuch erstellen"))
